### ISSUE TITLE
Przycisk "Zapłać za zamówienie" jest zawsze aktywny

### ISSUE THREAD

**Issue by mkutyba** [dotpay/Magento-1.x#10]
W redirect.phtml jest fragment JS:

```
if(jQuery('#dotpay_dotpay_redirection_form #chk').val() == '')
    jQuery('#dotpay_dotpay_redirection_form #submit').attr('disabled', true);
```

który ma za zadanie blokowanie przycisku, jeśli nie wybrano kanału płatności.
Jednak w DOM nie ma pola #chk dlatego ten warunek nie zadziała i przycisk jest aktywny od razu po załadowaniu strony.

**Comment by MrBloodyJohn** [comment]
Fixed in [v1.0.4](https://github.com/dotpay/Magento-1.x/releases/tag/v1.0.4).
